export const API_ROUTES = {
  AUTH: {
    GENERATE_OTP: "/generate-otp",
    REGISTER: "/register",
    LOGIN: "/login",
    LOGOUT: "/logout",
    VERIFY_OTP: "/verify-otp",
    GOOGLE_LOGIN: "/google-login",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    GOOGLE_WORKER_LOGIN: "/google-auth",
    WORKER_IS_VERIFIED: "/isVerified",
    REFRESH_TOKEN: "/refresh-token",
  },
  USER: {
    DETAILS: "/profile/userDetails",
    UPDATE: "/profile/updateUserDetails",
    CHANGE_PASSWORD: "/profile/changePassword",
    WALLET_DATA: "/profile/walletData",
    TRANSACTIONS: "/profile/transactions",
  },
  WORKER: {
    GET_SLOT: (email: string) => `/profile/slot?email=${email}`,
    UPDATE_SLOT: "/profile/slot/update",
    DETAILS: "/profile/details",
    UPDATE: "/profile/update",
    CHANGE_PASSWORD: "/profile/changePassword",
    CALENDAR_GET: "/calender/getData",
    CALENDAR_UPDATE: "/calender/update",
    WALLET_DATA: "/profile/walletData",
    TRANSACTIONS: "/profile/transactions",
    AVAILABILITY: (workerId: string) => `/workers/availability?workerId=${workerId}`,
    NEARBY: "/workers/nearby",
    PROFILE: "/workers/workerProfile",
  },
  ADMIN: {
    GET_USERS: "/users",
    UPDATE_USER_STATUS: (userId: string) => `/users/${userId}/status`,
    GET_WORKERS: "/workers",
    UPDATE_WORKER_STATUS: (workerId: string) => `/workers/${workerId}/status`,
    GET_UNVERIFIED_WORKERS: "/workers/unverified",
    VERIFY_WORKER: (workerId: string) => `/workers/${workerId}/unverified`,
    WALLET_DATA: "/wallet/walletData",
    TRANSACTIONS: "/wallet/transactions",
  },
  BOOKING: {
    BASIC_DETAILS: "/basicBookingDetails",
    GET_DETAILS: "/getBoookingDetails",
    GET_ADMIN_BOOKINGS: "/bookings",
    GET_ADMIN_BOOKING_DETAILS: (bookingId: string) => `/booking/${bookingId}`,
    ONGOING: "/bookings/ongoing",
    ONGOING_DETAILS: (bookingId: string) => `/bookings/ongoing/${bookingId}`,
    CANCEL: (bookingId: string) => `/booking/${bookingId}/cancel`,
    SERVICE_APPROVE: "/service/approve",
    SERVICE_REJECT: "/service/reject",
    SERVICE_REQUESTS: "/service/requests",
    SERVICE_APPROVEDS: "/service/approveds",
    SERVICE_APPROVEDS_DETAILS: (bookingId: string) => `/service/approveds/${bookingId}`,
    REACH_LOCATION: (bookingId: string) => `/service/reach-location/${bookingId}`,
    VERIFY_WORKER: "/service/verify-worker",
    WORK_COMPLETED: "/service/work-complated",
    ALL_BOOKINGS: "/service/allBookings",
  },
  PAYMENT: {
    CREATE_INTENT: "/payment/create-payment-intent",
    WEBHOOK: "/payment/webhook",
    VERIFY: (bookingId: string, type: string) => `/payment/verify?bookingId=${bookingId}&paymentType=${type}`,
    WALLET_PAYMENT: "/wallet/payment",
  },
  REVIEW: {
    ADD: "/review/addReview",
    GET_ADMIN_REVIEWS: "/reviews",
  },
  CHAT: {
    GET_ID: "/chat/chatId",
    HISTORY: "/chat/chatHistory",
    INBOX: "/chat/chatInbox",
  },
  NOTIFICATION: {
    GET: "/notifications",
    MARK_READ: (notificationId: string) => `/notifications/${notificationId}/read`,
    MARK_ALL_READ: "/notifications/read-all",
  },
  SERVICE: {
    GET_SERVICE: "/getService",
    GET_SERVICE_NAMES: "/getserviceNames",
    GET_ADMIN_SERVICES: "/services",
    CREATE: "/services/create",
    UPDATE_STATUS: (id: string) => `/services/${id}/status`,
  },
  CLOUDINARY: {
    SIGNATURE: "/cloudinary-signature",
    AUTO_UPLOAD_URL: (cloudName: string) => `https://api.cloudinary.com/v1_1/${cloudName}/auto/upload`,
    IMAGE_UPLOAD_URL: (cloudName: string) => `https://api.cloudinary.com/v1_1/${cloudName}/image/upload`,
  },
  LOCATION: {
    REVERSE_GEOCODE: (lat: number | string, lng: number | string) =>
      `https://nominatim.openstreetmap.org/reverse?lat=${lat}&lon=${lng}&format=json&accept-language=en`,
    REVERSE_GEOCODE_WITH_DETAILS: (lat: number | string, lng: number | string) =>
      `https://nominatim.openstreetmap.org/reverse?format=json&lat=${lat}&lon=${lng}&addressdetails=1&accept-language=en`,
    SEARCH: (query: string, limit: number) =>
      `https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(query)}&limit=${limit}&accept-language=en`,
    SEARCH_WITH_DETAILS: (query: string, limit: number) =>
      `https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(query)}&limit=${limit}&addressdetails=1&accept-language=en`,
    DRIVING_CAR: (startLng: number | string, startLat: number | string, endLng: number | string, endLat: number | string) =>
      `https://api.openrouteservice.org/v2/directions/driving-car?start=${startLng},${startLat}&end=${endLng},${endLat}`,
    GET_ADDRESSES: "/addresses",
    ADD_ADDRESS: "/addAddress",
    SET_PRIMARY: "/address/setPrimary",
  },
  DASHBOARD: {
    ADMIN: "/dashboard",
    WORKER: "/dashboard",
  },
} as const;
