export const API_ENDPOINTS = {
  ADMIN: {
    GET_USERS: "/users",
    UPDATE_USER_STATUS: (userId: string) => `/users/${userId}/status`,
    GET_WORKERS: "/workers",
    UPDATE_WORKER_STATUS: (workerId: string) => `/workers/${workerId}/status`,
    GET_UNVERIFIED_WORKERS: "/workers/unverified",
    VERIFY_WORKER: (workerId: string) => `/workers/${workerId}/unverified`,
    GET_SERVICES: "/services",
    CLOUDINARY_SIGNATURE: "/cloudinary-signature",
    CREATE_SERVICE: "/services/create",
    UPDATE_SERVICE_STATUS: (id: string) => `/services/${id}/status`,
  },

  AUTH: {
    GENERATE_OTP: "/generate-otp",
    REGISTER: "/register",
    LOGIN: "/login",
    LOGOUT: "/logout",
    VERIFY_OTP: "/verify-otp",
    GOOGLE_LOGIN: "/google-login",
    RESET_PASSWORD_LINK: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    GET_SERVICE_NAMES: "/getserviceNames",
    GET_SERVICE: "/getService",
    WORKER_IS_VERIFIED: "/isVerified",
  },

  USER: {
    PROFILE_DETAILS: "/profile/userDetails",
    UPDATE_PROFILE: "/profile/updateUserDetails",
    NEARBY_WORKERS: "/workers/nearby",
    WORKER_AVAILABILITY: "/workers/availability",
    ADDRESS_LIST: "/addresses",
    ADD_ADDRESS: "/addAddress",
    SET_PRIMARY_ADDRESS: "/address/setPrimary",
    BASIC_BOOKING: "/basicBookingDetails",
    BOOKING_DETAILS: "/getBoookingDetails",
    CREATE_PAYMENT_INTENT: "/payment/create-payment-intent",
    UPDATE_PAYMENT_STATUS: "/payment/webhook",
    CHANGE_PASSWORD: "/profile/changePassword",
    VERIFY_PAYMENT: "/payment/verify",
  },

  WORKER: {
    GET_SLOT: "/profile/slot",
    UPDATE_SLOT: "/profile/slot/update",
    PROFILE_DETAILS: "/profile/details",
    UPDATE_PROFILE: "/profile/update",
    CHANGE_PASSWORD: "/profile/changePassword",
    CALENDAR_GET: "/calender/getData",
    CALENDAR_UPDATE: "/calender/update",
    SERVICE_APPROVE: "/service/approve",
    SERVICE_REJECT: "/service/reject",
    SERVICE_REQUEST: "/service/requests",
    CLOUDINARY_SIGNATURE: "/cloudinary-signature",
  },
};
